clc;
clear;
close all;

% COMPARE_VALIDATED_HALO_MANIFOLDS
% Load saved validated halo members and compare their manifold structure.

mu = 0.012150585609624;

orbitNames = { ...
    'halo_L1_north_small', ...
    'halo_L1_north_medium', ...
    'halo_L1_north_large'};

eps0 = 2e-5;
tfStable = 3.0;
tfUnstable = 3.0;
numPhaseSamples = 30;

nOrb = numel(orbitNames);
manifolds = cell(nOrb,1);
orbits = cell(nOrb,1);

fprintf('\nComparing validated halo manifold cases\n');
fprintf('--------------------------------------\n');

for k = 1:nOrb
    S = astro.periodic.loadValidatedOrbit(orbitNames{k});

    orbit = astro.periodic.buildOrbitStruct(S.state0, S.T, S.mu, ...
        struct('family', S.family, ...
               'libr', S.libr, ...
               'system', 'earth-moon', ...
               'source', S.source, ...
               'dimension', '3D'), ...
        struct('verbose', true));

    man = astro.manifolds.generatePeriodicOrbitManifolds(orbit, S.mu, ...
        struct('eps0', eps0, ...
               'tfStable', tfStable, ...
               'tfUnstable', tfUnstable, ...
               'numPhaseSamples', numPhaseSamples, ...
               'includeBothSigns', true, ...
               'normalizeMode', 'position', ...
               'validateOrbit', true, ...
               'verbose', true));

    manifolds{k} = man;
    orbits{k} = orbit;

    fprintf('\nCase: %s\n', orbitNames{k});
    fprintf('  closure error          = %.3e\n', orbit.closureError);
    fprintf('  max stable Jacobi drift   = %.3e\n', man.maxJacobiDriftStable);
    fprintf('  max unstable Jacobi drift = %.3e\n', man.maxJacobiDriftUnstable);
end

%% ------------------------------------------------------------------------
% 3D orbit comparison
% -------------------------------------------------------------------------
fig1 = figure;
ax1 = axes(fig1);
hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');

for k = 1:nOrb
    X = orbits{k}.x;
    plot3(ax1, X(:,1), X(:,2), X(:,3), 'LineWidth', 2.0);
end

L = astro.cr3bp.lagrangePoints(mu);
plot3(ax1, -mu, 0, 0, 'ko', 'MarkerFaceColor','k', 'MarkerSize', 6);
plot3(ax1, 1-mu, 0, 0, 'o', ...
    'Color',[0.4 0.4 0.4], ...
    'MarkerFaceColor',[0.7 0.7 0.7], ...
    'MarkerSize', 8);
plot3(ax1, L.L1(1), L.L1(2), L.L1(3), 'yo', ...
    'MarkerFaceColor','y', 'MarkerSize', 7);

axis(ax1,'equal');
xlabel(ax1,'x');
ylabel(ax1,'y');
zlabel(ax1,'z');
title(ax1,'Validated halo orbit database comparison');
view(ax1,[35 25]);
legend(ax1, [orbitNames, {'Earth','Moon','L_1'}], 'Interpreter','none', 'Location','best');

%% ------------------------------------------------------------------------
% 3D manifold comparison: one figure per saved member
% -------------------------------------------------------------------------
for k = 1:nOrb
    man = manifolds{k};
    orbit = orbits{k};

    fig = figure;
    ax = axes(fig);
    hold(ax,'on');
    grid(ax,'on');
    box(ax,'on');

    hU = astro.plot.plotManifoldFamily3D(man.unstable, struct( ...
        'ax', ax, ...
        'Color', [1 0 0], ...
        'LineWidth', 0.8, ...
        'ShowOrbit', false, ...
        'ShowPrimaries', false, ...
        'ShowLibrationPoints', false));

    hS = astro.plot.plotManifoldFamily3D(man.stable, struct( ...
        'ax', ax, ...
        'Color', [0 0 1], ...
        'LineWidth', 0.8, ...
        'ShowOrbit', false, ...
        'ShowPrimaries', false, ...
        'ShowLibrationPoints', false));

    hOrbit = plot3(ax, orbit.x(:,1), orbit.x(:,2), orbit.x(:,3), ...
        'k', 'LineWidth', 2.0);

    hEarth = plot3(ax, -mu, 0, 0, 'ko', 'MarkerFaceColor','k', 'MarkerSize', 6);
    hMoon  = plot3(ax, 1-mu, 0, 0, 'o', ...
        'Color',[0.4 0.4 0.4], ...
        'MarkerFaceColor',[0.7 0.7 0.7], ...
        'MarkerSize', 8);
    hL1 = plot3(ax, L.L1(1), L.L1(2), L.L1(3), 'yo', ...
        'MarkerFaceColor','y', 'MarkerSize', 7);

    axis(ax,'equal');
    xlabel(ax,'x');
    ylabel(ax,'y');
    zlabel(ax,'z');
    title(ax, sprintf('Stable/unstable manifolds: %s', orbitNames{k}), ...
        'Interpreter','none');
    view(ax,[35 25]);

    legend(ax, ...
        [hU.branch(1), hS.branch(1), hOrbit, hEarth, hMoon, hL1], ...
        {'Unstable manifold', 'Stable manifold', 'Periodic orbit', ...
         'Earth', 'Moon', 'L_1'}, ...
        'Location', 'best');
end