clc;
clear;
close all;

% EX_UNIFIED_PERIODIC_ORBIT_MANIFOLDS
% First unified driver for any periodic orbit.
%
% For now:
%   - loads a validated planar Lyapunov orbit if present
%   - otherwise fetches a JPL seed and corrects it
%   - validates orbit
%   - generates stable/unstable manifolds
%   - plots in 2D and 3D-compatible style

mu = 0.012150585609624;
libr = 1;

validatedFile = sprintf('data/validated/planarLyapunov_L%d_validated.mat', libr);

%% ------------------------------------------------------------------------
% Build/load orbit
% -------------------------------------------------------------------------
if exist(validatedFile, 'file')
    S = load(validatedFile);
    state0 = S.state0;
    T = S.T;

    fprintf('Loaded validated orbit from %s\n', validatedFile);

else
    seed = astro.cr3bp.getPlanarLyapunovSeed('jpl', ...
        'sys', 'earth-moon', ...
        'family', 'lyapunov', ...
        'libr', libr, ...
        'index', 1);

    fprintf('Using seed from: %s\n', seed.source);
    fprintf('  x0_seed = %.16f\n', seed.x0);
    fprintf('  vy0_seed = %.16f\n', seed.vy0);
    fprintf('  T_seed = %.16f\n', seed.T);

    corr = astro.cr3bp.differentialCorrectionPlanarLyapunov( ...
        seed.x0, seed.vy0, mu, 30, 1e-12);

    if ~corr.converged
        error('Differential correction did not converge.');
    end

    state0 = corr.state0;
    T = corr.period;
end

orbit = astro.manifolds.buildOrbitStruct(state0, T, mu, ...
    struct('family','lyapunov', ...
           'libr', libr, ...
           'system','earth-moon', ...
           'source','unified driver', ...
           'dimension','2D'), ...
    struct('verbose', true));

%% ------------------------------------------------------------------------
% Generate manifolds
% -------------------------------------------------------------------------
man = astro.manifolds.generatePeriodicOrbitManifolds(orbit, mu, ...
    struct('eps0', 2e-5, ...
           'tfStable', 5.0, ...
           'tfUnstable', 5.0, ...
           'numPhaseSamples', 25, ...
           'includeBothSigns', true, ...
           'normalizeMode', 'position', ...
           'validateOrbit', true, ...
           'verbose', true));

%% ------------------------------------------------------------------------
% 2D plot
% -------------------------------------------------------------------------
fig = figure;
ax = axes(fig);
hold(ax,'on');
grid(ax,'on');

hU = astro.plot.plotManifoldFamily2D(man.unstable, struct( ...
    'ax', ax, ...
    'Color', 'r', ...
    'LineWidth', 0.8, ...
    'ShowOrbit', false, ...
    'ShowPrimaries', false));

hS = astro.plot.plotManifoldFamily2D(man.stable, struct( ...
    'ax', ax, ...
    'Color', 'b', ...
    'LineWidth', 0.8, ...
    'ShowOrbit', false, ...
    'ShowPrimaries', false));

hOrbit = plot(ax, orbit.x(:,1), orbit.x(:,2), 'k', 'LineWidth', 2.0);

L = astro.cr3bp.lagrangePoints(mu);
hEarth = plot(ax, -mu, 0, 'ko', 'MarkerFaceColor','k', 'MarkerSize', 6);
hMoon  = plot(ax, 1-mu, 0, 'o', ...
    'Color',[0.4 0.4 0.4], ...
    'MarkerFaceColor',[0.7 0.7 0.7], ...
    'MarkerSize', 8);
hL1 = plot(ax, L.L1(1), L.L1(2), 'yo', 'MarkerFaceColor','y', 'MarkerSize', 7);
hL2 = plot(ax, L.L2(1), L.L2(2), 'co', 'MarkerFaceColor','c', 'MarkerSize', 7);

axis(ax,'equal');
xlabel(ax,'x');
ylabel(ax,'y');
title(ax, sprintf('Unified manifold generation around planar L%d orbit', libr));

legend(ax, ...
    [hU.branch(1), hS.branch(1), hOrbit, hEarth, hMoon, hL1, hL2], ...
    {'Unstable manifold', 'Stable manifold', 'Periodic orbit', ...
     'Earth', 'Moon', 'L_1', 'L_2'}, ...
    'Location', 'best');

%% ------------------------------------------------------------------------
% 3D plot using same manifolds
% -------------------------------------------------------------------------
fig3 = figure;
ax3 = axes(fig3);
hold(ax3,'on');
grid(ax3,'on');

astro.plot.plotManifoldFamily3D(man.unstable, struct( ...
    'ax', ax3, ...
    'Color', [1 0 0], ...
    'LineWidth', 0.8, ...
    'ShowOrbit', false, ...
    'ShowPrimaries', false, ...
    'ShowLibrationPoints', false));

astro.plot.plotManifoldFamily3D(man.stable, struct( ...
    'ax', ax3, ...
    'Color', [0 0 1], ...
    'LineWidth', 0.8, ...
    'ShowOrbit', false, ...
    'ShowPrimaries', false, ...
    'ShowLibrationPoints', false));

plot3(ax3, orbit.x(:,1), orbit.x(:,2), orbit.x(:,3), 'k', 'LineWidth', 2.0);
plot3(ax3, -mu, 0, 0, 'ko', 'MarkerFaceColor','k', 'MarkerSize', 6);
plot3(ax3, 1-mu, 0, 0, 'o', ...
    'Color',[0.4 0.4 0.4], ...
    'MarkerFaceColor',[0.7 0.7 0.7], ...
    'MarkerSize', 8);

axis(ax3,'equal');
xlabel(ax3,'x');
ylabel(ax3,'y');
zlabel(ax3,'z');
title(ax3, sprintf('Unified 3D manifold plotting around planar L%d orbit', libr));
view(ax3, [35 25]);