clc;
clear;
close all;

% VALIDATE_HALO_MANIFOLDS
% Load a validated halo orbit and generate stable/unstable manifolds.

orbitName = 'halo_L1_north';

S = astro.periodic.loadValidatedOrbit(orbitName);

orbit = astro.periodic.buildOrbitStruct(S.state0, S.T, S.mu, ...
    struct('family', S.family, ...
           'libr', S.libr, ...
           'system', 'earth-moon', ...
           'source', S.source, ...
           'dimension', '3D'), ...
    struct('verbose', true));

man = astro.manifolds.generatePeriodicOrbitManifolds(orbit, S.mu, ...
    struct('eps0', 2e-5, ...
           'tfStable', 3.0, ...
           'tfUnstable', 3.0, ...
           'numPhaseSamples', 30, ...
           'includeBothSigns', true, ...
           'normalizeMode', 'position', ...
           'validateOrbit', true, ...
           'verbose', true));

fig = figure;
ax = axes(fig);
hold(ax,'on');
grid(ax,'on');
box(ax,'on');

hU = astro.plot.plotManifoldFamily3D(man.unstable, struct( ...
    'ax', ax, ...
    'Color', [1 0 0], ...
    'LineWidth', 0.8, ...
    'ShowOrbit', false, ...
    'ShowPrimaries', false, ...
    'ShowLibrationPoints', false));

hS = astro.plot.plotManifoldFamily3D(man.stable, struct( ...
    'ax', ax, ...
    'Color', [0 0 1], ...
    'LineWidth', 0.8, ...
    'ShowOrbit', false, ...
    'ShowPrimaries', false, ...
    'ShowLibrationPoints', false));

hOrbit = plot3(ax, orbit.x(:,1), orbit.x(:,2), orbit.x(:,3), 'k', 'LineWidth', 2.0);

L = astro.cr3bp.lagrangePoints(S.mu);
hEarth = plot3(ax, -S.mu, 0, 0, 'ko', 'MarkerFaceColor','k', 'MarkerSize', 6);
hMoon  = plot3(ax, 1-S.mu, 0, 0, 'o', ...
    'Color',[0.4 0.4 0.4], ...
    'MarkerFaceColor',[0.7 0.7 0.7], ...
    'MarkerSize', 8);
hL1 = plot3(ax, L.L1(1), L.L1(2), L.L1(3), 'yo', 'MarkerFaceColor','y', 'MarkerSize', 7);
hL2 = plot3(ax, L.L2(1), L.L2(2), L.L2(3), 'co', 'MarkerFaceColor','c', 'MarkerSize', 7);

axis(ax,'equal');
xlabel(ax,'x');
ylabel(ax,'y');
zlabel(ax,'z');
title(ax, sprintf('Validated %s: stable and unstable manifolds', orbitName), ...
    'Interpreter', 'none');
view(ax,[35 25]);

legend(ax, ...
    [hU.branch(1), hS.branch(1), hOrbit, hEarth, hMoon, hL1, hL2], ...
    {'Unstable manifold', 'Stable manifold', 'Periodic orbit', ...
     'Earth', 'Moon', 'L_1', 'L_2'}, ...
    'Location', 'best');